### PR TITLE
Small change for some functions

### PR DESCRIPTION
**Pull request by ALongSnake**
Modified the calculateUnits, isValidHashingFunction and isDirtyString
[bitrot.txt](https://github.com/ambv/bitrot/files/4172658/bitrot.txt)

### CODE REVIEW

**Comment by p1r473** [comment]
This is too big of a PR- they won't merge it.

**Comment by ambv** [comment]
LOL, this is indeed not a "small change". I'm interested in the Unicode normalization though, let's talk on the other pull request.

Thanks for this PR but I'll close it, it's too big.

**Comment by p1r473** [comment]
This project was me teaching myself Python. Unfortunately, I didn't realize some stuff about Git when I started- PR each individual change, don't upload so many times. At this point my fork is so big, I just don't have the time to get it all merged. Sorry!

**Comment by ambv** [comment]
That's all good. I should have paid attention back then!

**Pull request closed without merging**
