### PR TITLE
Pull 

### PR DESCRIPTION
**Pull request by p1r473**
* Added database vacuuming to shrink DB size on hard drive of old hashes that went missing
* Added logging to file using -g or ---log (on by default)
* Added grammar fixes
* Added a time elapsed counter
* Added email support for hash mismatch using -e or --email (on by default)
* Added option to ignore date modified (only checks hashes). Great for verifying backups for integrity (File Integrity Monitoring) using -t 2 or --test 2
* Added ability to specify hash function from command line. I found SHA512 to be just as fast as SHA1 on my machine using -a or --hashing-function
* Total size now printed in B, KB, MB, GB, TB
* Fixes for invalid characters in file names
* Better warning printing
* Integrates benshep's and liloman's latest changes
* Can now include and exclude at same time, and fixed logic. Exclude takes prescendence
* Now prints out ignored files at the end with verbosity level 4
* Added option to allow testing of only recent (default: last 1 day) of recently modified data (great for checking a backup you just synced for integrity) using -r or --recent
* Fixed bug when file doesn't have a valid modification timestamp
* Can now fix files that have invalid modification date, and rename files/dirs that have bad chars in name, using -f or --fix (dangerous)
* Can now create MD5 or SFV files using -c or --sfv

### CODE REVIEW

**Comment by ambv** [comment]
Hi man, thanks for your contributions! I cannot accept a huge diff like this and GitHub doesn't let me do cherry picks from your pull request. Please make separate pull requests on some of your changes and I'll merge them one by one.

**Comment by p1r473** [comment]
Seems the Github site doesn't support cherry picking commits, and I currently am not set up with the tool
Take a look at the following commits, its a good split of the major features:
Added logging to file
Added grammar fixes
Added a time elapsed counter
Added email support for hash mismatch
Added option to ignore date modified (only checks hashes). Great for verifying backups for integrity (File Integrity Monitoring)
Added ability to specify hash function from command line. I found SHA512 to be just as fast as SHA1 on my machine
Total size now printed in B, KB, MB, GB, TB
Fixes for invalid characters in file names
Can now include and exclude at same time, and fixed logic. Exclude takes prescendence
https://github.com/p1r473/bitrot/commit/f57aabed9f390bc695285a38f401b8c1271de858

Can now use --recent for only processing recent files 
https://github.com/ambv/bitrot/commit/7698c9020a04c76fa1ead41377c58a306570257a

Vacuums database to shrink after paths go missing
https://github.com/p1r473/bitrot/commit/57def4c916d74e234f129108c6fff1a43a9ce2da

Itll be a big project for me to try and chop that first commit up... maybe you can use the other pull requests I had submitted before this one?

I'll try to chop that first big commit up if I can find the time soon

**Comment by p1r473** [comment]
Give me some time and I'll break this into actual pull requests for each feature

**Comment by p1r473** [comment]
Unfortunately this is too big of a project to break this up piece by piece :( I do not have time. Sorry

**Pull request closed without merging**
