### PR TITLE
0.9.3

### PR DESCRIPTION
**Pull request by p1r473**
Added logging to file
Added grammar fixes
Added a time elapsed counter
Added email support for hash mismatch
Added option to ignore date modified (only checks hashes). Great for verifying backups for integrity (File Integrity Monitoring)
Added ability to specify hash function from command line. I found SHA512 to be just as fast as SHA1 on my machine
Total size now printed in B, KB, MB, GB, TB
Fixes for invalid characters in file names
Better warning printing
Integrates benshep's and liloman's latest changes

### CODE REVIEW

**Comment by ambv** [comment]
Did you intend to close this?

**Comment by rwoodpecker** [comment]
@p1r473 @ambv Please get your changes merged so we can benefit from them all.

**Comment by p1r473** [comment]
Sorry about that, kept accidently submitting hardcoded gmail credentials and having to delete the pull requests. Also hated the fact that I committed every 16 bug fixes, and rather merged into one

**Comment by p1r473** [comment]
> @p1r473 @ambv Please get your changes merged so we can benefit from them all.

Sorry I do not have the time required to break this apart into smaller changes in order to do a pull request

**Pull request closed without merging**
